# Informações do Projeto
site_name: Configurando Assinatura de E-mail
site_description: 'Configurando assinatura de E-mail'
site_author: 'Gefferson Balles'
site_url: 'http://gs.io/docs'

# Documentos e Temas
docs_dir: 'docs'
theme : 'material'

# Copyright
copyright: '© 2017 GS'

# Opções
extra:
  palette:
    primary: 'green'
    accent: 'light green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true

extra_css:
    - css/extra.css


# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Paginas
pages:
  - 'Home': 
    - 'Início': ''
    - 'Configurando Assinatura': 'assinatura.md'